### ISSUE TITLE
06- función potencia.

### ISSUE THREAD

**Issue by tomasescobar24** [ispc-programador2022/a5g3-a5g3#9]
Función que retorna la potencia del primero elevado al segundo parámetros.

**Comment by IAferaboli** [comment]
Hecho y Pushed

**Comment by juniors90** [comment]
La consigna dice `Función que retorna la potencia del primero elevado al segundo parámetros` pero está función no retorna lo que se pide. Solamente imprime por consola el valor.
Además hay que manejar las excepciones. Creo que te va a salir. Sino pregunta y te ayudamos. Éxitos 💪🏼

**Comment by IAferaboli** [comment]
Juan, modificado lo de "print" por "return".. Gracias por la corrección.. No logro comprender la referencia a las excepciones, agradezco luz en el tema

**Comment by juniors90** [comment]
Tu código es el siguiente:

```python
#Función que retorna la potencia del primero elevado al segundo parámetro.

def potencia():
  base= int(input("Ingrese la base: "))
  exponente= int(input("Ingrese el exponente: "))
  return base**exponente
```

Primero que nada, la consigna dice:

*6- función potencia, retorna la potencia del primero elevado al segundo parámetros.*

Distinto sería si dijera:

*6- función potencia,  solicita al usuario que ingrese dos números y luego retorna la potencia del primero elevado al segundo parámetros.*

En ningún momento aclara que hay que solicitar al usuario el input de los números, por lo cual me imagino la siguiente función:

```python
#Función que retorna la potencia del primero elevado al segundo parámetro.

def potencia(base: float, exponente: float) -> float:
    return base**exponente
```

Aún así, está función sigue teniendo errores ya que si ejecutamos `potencia(base=0, exponente=0)` resulta que 0 elevado a la 0 no existe. Ahí tendrías que manejar esa excepción según lo aprendido en CISCO (o googleando "¿Cómo manejar excepciones en Python?").

Y así, siempre debes:
- leer bien los requerimientos.
- pensar el algoritmo teniendo en cuenta todos los escenarios posibles en el cual va a ser utilizado tu código.
- escribir tu código (si es con buenas prácticas mejor).

Cualquier cosa pregunta nomás. Éxitos.

**Comment by IAferaboli** [comment]
Maravilloso Juan, super valiosa la observación y corrección.. Agradezco! Iré a por ello.

**Comment by ferrsil** [comment]
Hay que cambiar las variables por: La Base x a y  el Exponente x b. según esta en la función ing2i que subió un compañero. Saludos

**Comment by juniors90** [comment]
El nombre de las variables está bien porque hay que programar las funciones de manera independiente unas de otras.
Por último, se arma el programa llamado `a5g3.py` en el cual se llama a todas las funciones. Es en ese momento en el cual debemos hacer que la variables `base` y `exponentes` sean igual a `x` e `y`, respectivamente.
Para eso podemos usar programación orientada a objetos, sería la solución más óptima.

**Comment by ferrsil** [comment]
No podemos usar objetos están en el segundo cuatrimestre

**Comment by juniors90** [comment]
Ok

**Comment by IAferaboli** [comment]
Modificados los nombres de las variables..
En cuanto a la excepción de  0**0, matemáticamente da 1, por lo que no sería una excepción.

**Comment by juniors90** [comment]
> En cuanto a la excepción de 0**0, matemáticamente da 1

No lo sé Rick.

**Comment by IAferaboli** [comment]
En sí es una indeterminación. Pero en el sandbox de Cisco, al ejecutarlo te da 1

**Comment by juniors90** [comment]
Ok
